### ISSUE TITLE
Constant redrawing of the map with offline source if a fractional zoom is set

### ISSUE THREAD

**Issue by slavat** [mapbox/DEPRECATED-mapbox-ios-sdk#110]
I'm using a RMDBMapSource for an offline map. When I set a fractional zoom using a pinch gesture the map starts constantly redrawing tiles from the nearest integer zoom levels. For example if I zoom to somewhere between levels 13 and 14, I see tiles from levels 13 and 14 being drawn one after the other.

After some investigation I found out that this bug is introduced in the following commit: https://github.com/mapbox/mapbox-ios-sdk/commit/a90ff6c7f9c4dcd042d02562502a90cb7c230e92

I can reproduce it on the iPad simulator and the iPad 3.

**Comment by andreacremaschi** [comment]
Hi,this is the same issue I had with RMMBTilesSource, I fixed this in pull request #108.A tile cache mechanism was introduced with a merge from upstream, but the related code wasn't added in MapBox specific tilesources classes.You may take a look at my code, copy and paste in RMDBMapSource imageForTile:inCache: and see if it helps!

----Messaggio originale----

Da: notifications@github.com

Data: 03/09/2012 12.04

A: "mapbox/mapbox-ios-sdk"mapbox-ios-sdk@noreply.github.com

Ogg: [mapbox-ios-sdk] Constant redrawing of the map with offline source if a fractional zoom is set (#110)

I'm using a RMDBMapSource for an offline map. When I set a fractional zoom using a pinch gesture the map starts constantly redrawing tiles from the nearest integer zoom levels. For example if I zoom to somewhere between levels 13 and 14, I see tiles from levels 13 and 14 being drawn one after the other.

After some investigation I found out that this bug is introduced in the following commit: https://github.com/mapbox/mapbox-ios-sdk/commit/a90ff6c7f9c4dcd042d02562502a90cb7c230e92

I can reproduce it on the iPad simulator and the iPad 3.

```
          —

          Reply to this email directly or view it on GitHub.
```

**Comment by andreacremaschi** [comment]
Sorry, the symptoms are the same, but now as I can see the code missing in RMMBTilesSource is already there in RMDBMapSource.

**Comment by incanus** [comment]
I've fixed this just now. As @slavat noted, it was an oversight to introduce the new caching-based/async performance code for local tile sources, so I've fixed that now. I will address @andreacremaschi's issue/pull request separate over there.
