### ISSUE TITLE
add support for Bing tiles

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#114]
Per licensing agreements, it would be good to get this in project & upstream for compositing possibilities.

**Comment by incanus** [comment]
Basic API overview of seems to be here: http://msdn.microsoft.com/en-us/library/ff701716.aspx

It's not setup like most of our common tile sources, as you specify a zoom and center coordinate and get back XML or JSON that you then parse to get a URL for the map tile, which you then fetch. Other sources just take a query and give back tile imagery. 

But it seems to be doable.

**Comment by alfredjim** [comment]
In the old route-me there was a direct access to the tiles.

**Comment by incanus** [comment]
Thanks @alfredjim, I'll check it out.

**Comment by VeeraSrinivasan** [comment]
Do you have a timeline for when Bing tile support would be available? We are in the process of finalizing the choice of map sdk (iOS). Aerial and Satellite imagery is important to us. Since OpenStreet does not support these imageries, we would like to use Bing tiles (we are already Bing customer). Is this possible and when?

**Comment by incanus** [comment]
@VeeraSrinivasan, I've just added support for Bing. 

Note that it is up to you to determine if you can cache the retrieved tiles and/or if you can composite them with other sources. According to my brief reading of Microsoft's terms of service, the answer to both is no, but I could be wrong.

**Comment by Looking4Cache** [comment]
I was in contact with Microsoft about the legal issues about using Bing Maps. Here what I get (as I understand it):
- If the app can be accessed without limitations and without a monthly/annual fee, the Bing Maps can used without charge. "Without limitations" means that there is no user registration or user account needed to use the app. Initial paying the app in the AppStore is ok.
- With the Free Bing Maps Account (where you pay nothing) you can only use the iOS SDK or the Ajax Control. This is because Bing divides the API requests in "free" and "not free" requests. If you are using the iOS SDK to open a API session, the API requests to getting the tiles are "free". If you using the REST API without the iOS SDK, the tile downloads/lookups are "not free".

So before I know that my first idea was to write a tile source which uses the REST API to get the "image metadata" and the tiles. Note: For this you have to provide the bing-maps-key through the API, the current tile source don´t use the API, it only downloads the tles.

Because I don´t want to pay for the tiles, I start try out embedding the Bing Maps iOS SDK in MapBox iOK SDK. I added a (dummy) tile source and a layer containing the BMMapView to MapBox. So the Bing Maps is between the Layers of MapBox and the (empty) tiles. If the MapView is zoomed and moved the BMMapView was updated. All worked nice, but my only problem is that the BMMapView don´t updates while the MapBox MapView is zoomed. It only updates the display as soon as the ScrollView is finish..

Best, Thorsten

**Comment by incanus** [comment]
@Looking4Cache, the tile source that I wrote does indeed use a Bing API key. Are you saying it's not doing something properly? Not sure I understand.

**Comment by Looking4Cache** [comment]
Hi,

sorry, there was an error on my side. I thought you just copied the Bing Maps Source from route-me. I just viewed the new source and see you properly use the Imagery Metadata with a Bing Map Key.

I just looked on the terms of use and the billing informations under http://msdn.microsoft.com/en-us/library/ff859477.aspx . Maybe my contact to the maplic address got me on a wrong way..

Thanks for the new tile source and sorry for the confusion,
Thorsten
