### ISSUE TITLE
double-tap zoom has poor icon move animation

### ISSUE THREAD

**Issue by tracyharton** [mapbox/DEPRECATED-mapbox-ios-sdk#116]
When you double-tap to zoom, icons slide to their correct position post-zoom instead of moving with the map.

**Comment by admmasters** [comment]
Yes seconded. This is pretty jarring and for an otherwise excellent SDK is a real deal breaker. :-(

**Comment by incanus** [comment]
To clarify, you are just seeing this on the first zoom, right? Or more frequently than that?

**Comment by admmasters** [comment]
Hi,

This occurs nearly all the time, although strangely not ALL the time. Very sporadic. The way we have set up our app is a map with 59 pins for different countries. Upon pressing a pin we are using the function [self.mapView zoomWithLatitudeLongitudeBoundsSouthWest:zoomBounds.southWest northEast:zoomBounds.northEast animated:YES] to zoom in. What happens is the map zooms in and then the pin repositions itself, looks really buggy...

**Comment by incanus** [comment]
I will have a look at this, but are either of you still seeing it with the latest `develop`?

**Comment by incanus** [comment]
I never see this with either programmatic zooms nor double-tap-to-zoom-in nor two-finger-tap-to-zoom-out. Does it seem to happen only at certain zoom levels? Certain numbers of annotations? In what types of scenarios -- `viewDidLoad`, `viewDidAppear:`, etc.?

**Comment by admmasters** [comment]
Hi. I will try and video this behaviour and send through when I get the chance.

**Comment by incanus** [comment]
This still happening for folks in the latest `develop`? Been doing a lot of work with annotation layers lately.

**Comment by admmasters** [comment]
Hi Justin this is still occurring for me, its not a deal breaker anymore, just a bit awkward at times.

M

**Comment by sobri909** [comment]
This appears to be due to the fact that `zoomToRect:animated:` has variable animation durations, but annotation movements are being animated with a consistent 0.3 duration. 

##### Roughly What's Happening (skipping irrelevant steps)
1. User double taps
2. `zoomByFactor:near:animated:YES`
3. `zoomToRect:animated:YES`, with variable and unknowable animation duration
4. `contentOffset` change is observed, which triggers fixed duration annotation animations
5. A **single** `scrollViewDidZoom:` call at the beginning of the zoom animation

##### The Problems
- `scrollViewDidZoom:` is essentially useless, as it doesn't repeatedly fire all the way through the zoom, like it does during pinch zooms.
- `zoomToRect:animated:` is a black box, with variable and unknowable animation durations.

##### A Solution

I suggest a custom `zoomToRect:animated:` with fixed animation duration, so that annotation movements can be exactly timed to match. @incanus If that sounds reasonable to you, I'll churn it out shortly.

##### Related

`setZoom:atCoordinate:animated:` suffers from a similar problem. In its case the annotations aren't animating at all, but instead snap to their final locations immediately (due to the single `scrollViewDidZoom:` event).

I've worked around that one [in this commit](https://github.com/seatgeek/mapbox-ios-sdk/commit/e96de239ff74e31ee34ac144fae74c9759a261f9), by using an `_ignoreZoomEvent` flag and an explicit annotation animations request.

**Comment by sobri909** [comment]
Okay, [here's a commit](https://github.com/seatgeek/mapbox-ios-sdk/commit/60b21e640e5b55185fdecff370e8523b9242b95b) that fixes it, with a custom `zoomToRect:animated:`. It reuses the same `_ignoreZoomEvent` flag as in the last commit. With this commit combined with the previous, all annotation animations are synchronised with zooms.

@incanus If it checks out with you, I'll submit them as a pull request on `develop`.

**Comment by incanus** [comment]
I like this @sobri909, fire away!

**Comment by incanus** [comment]
Closing in favor of the #198 pull request.
