### ISSUE TITLE
Accuracy circle not always correct, and possibly causes static circle to be shown in heading mode

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#118]
When entering heading mode there's a constant, non-moving circle around the location dot.

Screenshot:

https://dl.dropbox.com/u/44154592/Screen%20Shot%202012-09-13%20at%2013.17.07.png

**Comment by incanus** [comment]
iOS 6!!! ;-)

I'll check it out.

**Comment by russellquinn** [comment]
(Note that this is an app built against iOS SDK 5.x, but running on iOS 6.)

**Comment by incanus** [comment]
Hmm, I don't see it happen with either of my devices. However I can only build against iOS 6 now. I will try to dig up an older SDK.

**Comment by incanus** [comment]
Ok, give the above commit a try, keeping in mind that this is on the `develop` branch so other things are afoot there. If this fixes it, I will port that over to `release` and do a point update. 

This was related to changes over in #31 where we had to use duplicate views in order to get annotation z-ordering above the user location markers right.

**Comment by russellquinn** [comment]
Seems fixed!
