### ISSUE TITLE
improve offline mode documentation

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#225]
We need better clarification of the different ways that you can use maps offline. 
- MBTiles tile source
- RMTileCache for previously-downloaded tiles
- Costs (or lack thereof) associated with each

Could go at http://mapbox.com/mapbox-ios-sdk/#tile_caching__class (possibly renamed to _Offline Maps_).

**Comment by radven** [comment]
I am looking for best practices examples of how to implement offline support. I'd like to bundle full offline maps with the app as shipped so that it can work even if it is never online to do any initial downloading. But then I'd like to enable updating to newer versions on the occasions that the user is indeed online. I think MBTiles may be the way to go - but figuring out how to do the updates is a bit confusing.

**Comment by msealy** [comment]
Here is my own journey to the "truth" so to speak. I had a terrible misunderstanding of the way initWithMapId works. For some reason I got the impression that this method in conjunction with enabling cache would be smart enough to download tiles when online and reuse the cache when offline. This mistake was my undoing. Maybe the docs could make it more clearer to avoid the false impression. After much research and reviewing the many offline issues which were opened, I came across this article in particular http://support.mapbox.com/discussions/mapbox-ios-sdk/706-cache-maps-simply-doesnt-work. 

Here is the workflow that I settled on for offline access. Note that initWithMapId is not an option when offline as the app crashes. Even if this is fix to return a nil reference it still does not account for how the initialization routine works. This method simples fetches the tilejson describing your map (and NOT the tiles themselves) and NEVER from the cache.

1) Download your tilejson description by appending .json to the end of your mapId url.
2)  Save this as a resource in your project (e.g mapbox.json)
3) Initialized the mapboxsource

```
NSString *fullPath = [[NSBundle mainBundle] pathForResource:@"mapbox" ofType:@"json"];
NSString* tileJSON = [NSString stringWithContentsOfFile:fullPath encoding:NSASCIIStringEncoding error:&error];
RMMapBoxSource *tileSource = [[RMMapBoxSource alloc] initWithTileJSON:tileJSON];
```

4) Enable caching and set the source

```
[tileSource setCacheable:YES];    
[mapView setTileSource:tileSource];    
```

5) Eagerly fetch (some or all of your) tiles (optional)
You will need to implement the RMTileCacheBackgroundDelegate

```
for (id cache in mapView.tileCache.tileCaches)
{
    if ([cache isKindOfClass:[RMDatabaseCache class]])
    {
        RMDatabaseCache *dbCache = (RMDatabaseCache *)cache;
        DDLogVerbose(@"current cache size: %lld", dbCache.fileSize);
        if (dbCache.fileSize < 20000) 
        {
            [mapView.tileCache setBackgroundCacheDelegate:self];
            NSInteger minZoom = tileSource.minZoom;
            NSInteger maxZoom = tileSource.maxZoom; // here I am fetching all but this might be too much 
            [mapView.tileCache beginBackgroundCacheForTileSource:tileSource southWest:tileSource.latitudeLongitudeBoundingBox.southWest northEast:tileSource.latitudeLongitudeBoundingBox.northEast minZoom:minZoom maxZoom:maxZoom];
        }

        break;
    }
}
```

6) Configure your database cache either in code or in a plist
https://www.mapbox.com/mapbox-ios-sdk/#tile_caching__class

*\* VERY IMPORTANT **
Make sure to set useCachesDirectory to true in order to persist the cache to the temporary caches folder on the app as opposed to the documents folder. The latter would cause the tiles to be backed up to the user iCloud and could result in your app being rejected for improper use of the filesystem.

Hopefully this helps someone else.

**Comment by crarau** [comment]
Thanks for sharing this as I managed to get caching work.
It is was indeed difficult for me too as I was not understanding why caching doesn't work.
I've chosen Mapbox was explicitly for the offline caching.
Thanks again,
Ciprian.

**Comment by nejra** [comment]
@msealy you really helped me a lot, thank you for sharing this! I agree that mapbox documentation is not detailed enough

**Comment by msealy** [comment]
Happy to help.

**Comment by incanus** [comment]
Building atop the Route-Me code restricted this in certain ways that have been done better by [MBXMapKit](http://mapbox.com/mbxmapkit) and will be done better in [Mapbox GL](http://mapbox.com/mapbox.gl).

**Comment by paulthorsteinson** [comment]
@incanus I am using the Mapbox-iOS-SDK pod.  I did not realize there was an MBXMapKit one.  Does it handle offline maps in an easier fashion?

**Comment by incanus** [comment]
Yes, MBXMapKit has the concept of an offline map manager singleton and offline map documents that are self-contained SQLite databases. They are created by individual tiles getting downloaded into them. Read here for more: https://github.com/mapbox/mbxmapkit#features

**Comment by paulthorsteinson** [comment]
Update - I tried MBXMapKit but I was having weird crashes in the offline downloader, in particular if connectivity changed (ios 7 simulator).  In the end I took advantage of the mapbox ios sdk's ability to load mbtiles.  My maps are of buildings so I just use TileMill to generate the mbtiles, then download those to a device so they can then be used offline reliably.
