### ISSUE TITLE
RMMapView doesn't support Autolayout when creating from a storyboard

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#270]
Assigned to [MapBox iOS SDK #1219](http://support.mapbox.com/discussions/mapbox-ios-sdk/1219-rmmapview-doesnt-support-autolayout-when-creating-from-a-storyboard). As reported in Tender:

<blockquote><p>Steps to reproduce:</p>

<p>1) Create an ios 6.1 app in XCode with a storyboard
<br>2) Go to the file inspector on the storyboard and ensure that the "Use Autolayout" checkbox is checked
<br>3) Create a view in the storyboard and set the class to RMMapView
<br>4) Run the app. It will crash.  </p>

<p>Just before it crashes, you'll get a log message saying "CALayer bounds contains NaN: [nan nan; 0 0]'"
<br>The crash goes away if you uncheck the Use Autolayout option.
<br>I am using mapbox 1.03</p></blockquote>

**Comment by ghost** [comment]
I have the same problem.

Turning off AutoLayout is not an acceptable workaround for us, because we are actively using it elsewhere in the storyboard. Before I spend too much time on this: is there an alternative workaround?

Can you confirm whether the problem is to do with AutoLayout itself (so that programmatically adding the view and the same constraints will not help) or only to do with how AutoLayout is used within Storyboards?

**Comment by derekmpeterson** [comment]
I'm having this problem, too.  Disabling AutoLayout is not an acceptable solution in our case

**Comment by incanus** [comment]
I am seeing this issue in iOS 6 on Xcode 4.6.3. I am investigating.

**Comment by incanus** [comment]
For anyone following along at home and with possible insight, the deal is that with autolayout, an `RMMapView` doesn't have a frame during the `initWithCoder:`, `awakeFromNib`, or even the `updateConstraints` stages, so the contained `UIScrollView` equally does not, so its `contentSize` is invalid. This is used early on to calculate `_metersPerPixel` at a given zoom level, and normally is initialized/updated in KVO observing the `UIScrollView`'s `contentOffset` during programmatic use (vs. NIB-based). 

What we need is a stage _after_ the above routines, but _before_ general use is allowed, for NIB-based views so that this can be properly initialized. 

Still researching.

**Comment by ghost** [comment]
@incanus try `didMoveToWindow`

**Comment by incanus** [comment]
Cool @willerz-dotank, that was next on my list.

**Comment by incanus** [comment]
No dice. Logging at `didMoveToWindow` also yields: 

```
2013-08-20 09:09:52.359 Storyboard Test[34615:c07] <RMMapScrollView: 0x7576c10; baseClass = UIScrollView; frame = (0 0; 0 0); opaque = NO; gestureRecognizers = <NSArray: 0x7596830>; layer = <CALayer: 0x759e7b0>; contentOffset: {0, 0}>
2013-08-20 09:09:52.359 Storyboard Test[34615:c07] MapView at {0,0}-{0x0}
```

**Comment by incanus** [comment]
Ok, making some headway here. It's a combination of needing `autoresizingMask` on the scrollview and/or tile container, plus I'm still puzzling out some code in `layoutSubviews`, which does have the views sized appropriately.

**Comment by incanus** [comment]
Couple more parameters: 
- Doesn't happen in Xcode [REDACTED], only in Xcode 4.x. Might be a simulator bug. Do people see this on 6.x devices? 
- Doesn't happen when autolayout constraints are applied in code, which we mostly knew but I wanted to confirm.

**Comment by incanus** [comment]
Ok, pretty sure I have it. Please test the https://github.com/mapbox/mapbox-ios-sdk/tree/270-autolayout-storyboards branch for this.

**Comment by ghost** [comment]
@incanus it does occur on 6.x devices. Not sure why you think it doesn't happen when constraints are applied in code, as that made no difference in my testing; perhaps you had used `initWithFrame` or otherwise set the frame in addition to using constraints.

**Comment by ghost** [comment]
@incanus in VCs I put logic which needs a valid size in `viewDidLayoutSubviews`; I can't recall if `layoutSubviews` is still used with autolayout but if it is then

```
-(void)layoutSubviews
{
    [super layoutSubviews];
    // Code which needs valid sizes goes here
}
```

should work.

**Comment by Moux** [comment]
@incanus I can't help but wonder if this is related to bugs number #238 and #228 .   If this is the case, how is RMOpenStreetMapSource able to get around this?   Does looking there help?

**Comment by incanus** [comment]
Anyone have any feedback on the branch fix?

**Comment by Moux** [comment]
I still seem to have the same issue, when I create a map view with a CGRectZero size.

**Comment by incanus** [comment]
Ok, @Moux, I will check that out. Are you doing that just to test or for a valid reason? Just curious.

**Comment by Moux** [comment]
I am currently writing a Titanium module wrapping RMMapView.   The way this works is that I need to create an RMMapView that gets inserted into a Titanium view.   Then this view gets posted to the system and given a size only then.   I have been using OSM at creation time, then once the view is posted, I been switch the tilesource.

I'd much rather go straight to MapBox, rather than do this work twice, not to mention it would simplfy my code.

**Comment by mgraesser** [comment]
I think the branch fix will work because this is basically what I changed mine to do and I was having these crashes using storyboards and auto layout when I first started my app with offline maps and my app no longer crashes. My crashes were the exact error described above with the nan, nan. and the views not being valid yet. The one thing to note is on rotation didLayoutSubview is called again. I did add a check for an initial state so I did not reinitialize the source. It looks like you have a check there also.

```
 - (id)initWithCoder:(NSCoder *)aDecoder

{
...
    RMMapBoxSource *source = nil;
    [self performInitializationWithTilesource:source
                             centerCoordinate:coordinate
                                    zoomLevel:kDefaultInitialZoomLevel
                                 maxZoomLevel:kDefaultMaximumZoomLevel
                                 minZoomLevel:kDefaultMinimumZoomLevel
                              backgroundImage:nil];
...}
```

Added checks in 

```
- (void)performInitializationWithTilesource
...
    if (newTilesource) {
        if (initialTileSourceMinZoomLevel < newTilesource.minZoom) initialTileSourceMinZoomLevel = newTilesource.minZoom;
        if (initialTileSourceMaxZoomLevel > newTilesource.maxZoom) initialTileSourceMaxZoomLevel = newTilesource.maxZoom;
        [self setTileSource:newTilesource];
    }
...

// in my view controller 

-(void)viewDidLayoutSubviews {
...
//set my map source 
...
}

```

**Comment by rhysyngsun** [comment]
I can confirm that I was also seeing the crash in the simulator (XCode 4.6.2) for an app built for iOS 6.1 using version 1.0.3 and that the 270-autolayout-storyboards branch worked absolutely fine for me.

**Comment by incanus** [comment]
Merged into `develop`.
