### ISSUE TITLE
improve RMShape callout placement

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#285]
Assigned to [MapBox iOS SDK #1229](http://support.mapbox.com/discussions/mapbox-ios-sdk/1229-callout-on-rmshape). As reported in Tender:

<blockquote><p>Hi,</p>

<p>Showing callout at the top center of the annotation view's frame doesn't feels right for users. Callout should be shown from some real point on the shape.</p>

<p>I see two options here:</p>

<p>1. Calculate and set calloutOffset (pixels) from one of the shape's points (geo coordinates).
<br>2. Callout should be shown from annotation's coordinates which can be set manually as one of the shape's points.</p>

<p>Anybody have math for 1st option? Or how to achieve behaviour described in 2nd option?</p>

<p>I use MapBox iOS SDK 1.0.3 (binary). By the way: is it possible to use SMCalloutView directly with binary MapBox iOS SDK installation (can't find SMCalloutView.h in MapBox.framework headers)?</p></blockquote>

**Comment by mrabenhorst** [comment]
I am currently working on a solution for a project that requires this functionality. However, my intent is to put the callout flag up on the shape exactly where the user taps - rather than a manually predetermined point - which, for my project, would cause other problems.

I have resorted to adding a new method called selectAnnotation:animated:atPoint: which replaces the existing selectAnnotation:animated: method. (selectAnnotation:animated: now calls selectAnnotation:animated:atPoint: with CGPointZero as the point.) This new method will present the callout flag at the specific pixel point (if not CGPointZero) on the annotation, rather than at the default.

The math seems straight forward - calculate and convert the projected top-center of the RMShape's projectedBoundingBox and determine the displacement of the point tapped. Then assign that to _currentCallout.calloutOffset.

That works excellent for when the annotation is completely on the screen, but it becomes an issue when it isn't. In fact, it gets quite wacky sending the callout in very odd locations. Moreover, when I zoom into and out of the map, the callout stays at the same screen point, but changes it's location in the annotation's layer.

Any ideas as to why the flag is behaving that way?

Code below where `anAnnotation` is the annotation and `aPoint` is the pixel location of the tap.

``` Objective-C
RMProjectedPoint anAnnotationTC = RMProjectedPointMake(anAnnotation.projectedBoundingBox.origin.x+(anAnnotation.projectedBoundingBox.size.width/2), anAnnotation.projectedBoundingBox.origin.y+anAnnotation.projectedBoundingBox.size.height);
CGPoint anAnnotationTCPixel = [self projectedPointToPixel:anAnnotationTC];
CGPoint offsetInPixels = CGPointMake(aPoint.x - anAnnotationTCPixel.x, aPoint.y - anAnnotationTCPixel.y);
_currentCallout.calloutOffset = offsetInPixels;
```

**Comment by incanus** [comment]
This sounds like a decent approach. My guess as to why the callout is behaving that way, though, is because unlike markers, shapes get a scale transform applied during zooming, so the position of the callout layer within its superlayer (the shape) gets a little wacky. I'd suggest looking into moving the callout layer in response, but you will run into the same problems that I did over in https://github.com/mapbox/mapbox-ios-sdk/issues/421.

**Comment by mrabenhorst** [comment]
Sounds like the rabbit hole runs pretty deep with this. 

Since the layers keep resizing using a single-dimensional scale, that should mean that the callout will always remain in the same relative location in the superview. Normally, I have seen this handled by using callout displacement as a decimal percentage of the parent's view. Is there a reason why displacement is by pixels and not percentage? In theory, wouldn't this work if the displacement was by percentage?

**Comment by mrabenhorst** [comment]
As an experiment, I altered the displacement to be by percentage and not by pixel by changing a couple lines in SMCallout. It works great until the annotation's shape layer goes beyond the current screen view and gets trimmed (assumed performance enhancement). Then everything starts to break down because the w/h ratio becomes abnormal. 

From here I see two potential solutions:
1. Somehow access the untrimmed bounds for the shape layer and calculate displacement by percentage (not pixel displacement because bounds changes scale readily)
2. Pull the callout from the annotation's layer and assign it to the map's layer - a dramatic change for something like this.

Option 1 seems more realistic and I will pursue that first. That said, the ability to place callouts at any location on the map at any time also seems inviting. 

Any thoughts on the matter?

**Comment by mrabenhorst** [comment]
Another thought came to mind as I have been struggling over a solution. Would it be acceptable to calculate the position where the line was tapped (in projected space) and create an invisible 1px point annotation at that position to host a callout? That way the callout is satisfied because it has a parent and the annotation should always exist at the same location on the line. The callout would appear as if the user tapped on the line (the goal). Seems like a win-win situation.

**Comment by incanus** [comment]
We no longer support callouts on non-markers as of `1.2.0`.
