### ISSUE TITLE
Podspec dependency on FMDB == 2.0

### ISSUE THREAD

**Issue by ramonpoca** [mapbox/DEPRECATED-mapbox-ios-sdk#311]
Hi,

I have a project using FMDB w. cocoapods. Due to MapBox depending on strict FMDB 2.0, It's getting messed up. Current FMDB version is 2.1.

Could the dependency be raised to ~> 2.0?

**Comment by incanus** [comment]
I will take a look at this. I have a todo to bump up the dependencies already.

**Comment by incanus** [comment]
This is actually another issue: lack of namespacing in Objective-C. There is equally likely to be someone who needs FMDB to be < 2.0 for some reason. 

http://pdx.esri.com/blog/2013/12/13/namespacing-dependencies/ is a solution to this, but the overhead is still not ideal. 

Since FMDB is so small, I would recommend looking into possibly doing a search & replace on the symbol names to work around this. 

Future versions of the SDK will hopefully have less external dependencies, making this a bit smoother.
