### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by RyanCopley** [mapbox/DEPRECATED-mapbox-ios-sdk#400]
I haven't looked through every function, but I see these two methods:

```
RMMapView -setShowLogoBug: (BOOL);
RMMapView -setHideAttribution: (BOOL);
```

It is counterintuitive to have negative and positive logic in different places

**Comment by incanus** [comment]
This is because `setShowLogoBug:` was chosen to be more Cocoa-like as one might expect, but `setHideAttribution:` was chosen because we generally don't want people to hide it unless they know what they are doing. We have a surprising number of problems with people not crediting the OpenStreetMap and other data that our maps are based on and wanted a way to mentally reinforce this.
