### ISSUE TITLE
Cache doesn't work when there is a high-latency connection

### ISSUE THREAD

**Issue by TroyJ** [mapbox/DEPRECATED-mapbox-ios-sdk#405]
If you have a high-latency connection and navigate to an area of the map which isn't cached, all available download pipes become blocked. If you then navigate to an area which is in the cache, you will be staring at a blank map waiting for the download pipes to fail or complete. If timeout and retry are set to reasonable values, this could be minutes of waiting.

It seems to me that the very purpose of a cache is so the map performs well when there is a bad network connection, so this bug seems to defeat the purpose of having a cache.

It's possible to improve the performance (but not fix it) if we set the retry count to 1 (no retries), and the timeout to as small as reasonable for a "good" cellular connection... The result is that when the connection is "bad" the download pipes will be cleared as fast as possible, but the map is still not instantly responsive (as it should be in a cached area) - and has the added disadvantage that sometimes map tiles don't load correctly in normal situations (because they time out too fast).

This situation is especially bad when retry count is set to a high value - as the tiles seem to be retried in order of when they were requested, and not based on what's currently visible on the map. Perhaps this should be logged as a separate issue? The download "thread" should always be trying to download what makes the most sense - ie, trying to download tiles for any map view that's visible.

**Comment by incanus** [comment]
Yes, overall, there is not the concept of a priority-based queue and expiration of obsolete tiles. Tile loads are FIFO, where "in" is when they are first requested and "out" is when they finish loading. 

This requires a fair amount of re-architecting; however we are working on in a new version of the renderer. 

The difficulty in doing this in the current renderer is that it is based on Apple's `CATiledLayer`, which does not indicate when it is about to request certain tiles and when it no longer needs them, despite tracking this information internally. One would have to develop duplicate functionality that is in sync with its behaviors (for example, requesting lower-numbered zoom level tiles occasionally in order to draw _something_ to the screen while loading more detail) in order to manage such a queue.

**Comment by incanus** [comment]
I'm going to close this as not actionable right now, but being looked at to be addressed soon.

**Comment by TroyJ** [comment]
If it's closed, where can I track it?

**Comment by TroyJ** [comment]
Any suggestions on workarounds? And really rough feel on when it will be addressed? I have an idea on a possible workaround, but not sure if it's worth implementing if this will be fixed soon.

At the moment I'm considering upping the retry limit to something reasonable (a retry of "1" is too unreliable, I sometimes get trashed tiles). I can then try intercepting all map-tile requests using NSURLProtocol. If the user moves the map, I'll kill all existing connections, and keep killing them until there are no new connections (which I hope will clear out the queue). I can then request a refresh on the map, which will hopefully pull all requests from the cache (unless the user is unlucky enough to have some tiles that are not on cached in the current screen.) It's going to sacrifice alot of performance, but I think it will be reliable.
