### ISSUE TITLE
Heading compass not shown on views that don't use autolayout

### ISSUE THREAD

**Issue by namannik** [mapbox/DEPRECATED-mapbox-ios-sdk#406]
The heading compass doesn't show up in an `RMMapView` if its superview does not use autolayout.

**Comment by incanus** [comment]
Is this tested against `develop`?

**Comment by namannik** [comment]
Yes, this occurs in `develop`.

**Comment by incanus** [comment]
Hmm, so the compass is iOS 7+, but that also means the new view controller underlap behavior, which requires use of `topLayoutGuide` to correct. I'm not sure if there's a way around this without using autolayout...

**Comment by incanus** [comment]
Here's the relevant autolayout code: https://github.com/mapbox/mapbox-ios-sdk/blob/3223e01e0092ada7c32bf1df8f091b4b6e5f3972/MapView/Map/RMMapView.m#L510-L529

**Comment by namannik** [comment]
I thought that might be the answer.  I tried turning on autolayout, but it ends up causing problems in my use case that I can't seem to work around.  Not having the compass isn't a huge deal to me, but I thought it would be worth mentioning.

**Comment by incanus** [comment]
Thanks for the flag. 

As it is, we do some [voodoo](https://github.com/mapbox/mapbox-ios-sdk/blob/3223e01e0092ada7c32bf1df8f091b4b6e5f3972/MapView/Map/RMMapView.m#L482-L491) that I'm not super fond of in order to build constraints against the view controller, which should be out of our purview. But it was the only way to make the compass work at all. Apple doesn't provide a direct way for a view maintainer to "reach up" in this fashion and instead expects the app developer who owns the view controller to "reach down". However, a developer shouldn't have to care about the internals of my subviews, but alas.
