### ISSUE TITLE
RMMarker frames have twice the height of their content

### ISSUE THREAD

**Issue by MaximeLM** [mapbox/DEPRECATED-mapbox-ios-sdk#435]
I've noticed that RMMarker frames are twice as tall as their content. That makes selection difficult when annotations are close (yellow box is the frame of the top annotation) :
![capture decran 2014-04-13 a 00 38 12](https://cloud.githubusercontent.com/assets/5273410/2688304/2c9b6786-c293-11e3-9130-0c1fb49fce13.png)
Is this behavior intended ?

**Comment by incanus** [comment]
Yes, this is because the icons rendered as part of the [Mapbox API](https://www.mapbox.com/developers/api/static/#markers) do this so that the pin point is at the image center. However transparent portions shouldn't be getting hit tested anyway. Are you sure that the top pin's shadow isn't to blame @MaximeLM?
