### ISSUE TITLE
Selected annotation callout hidden when map pans and zooms

### ISSUE THREAD

**Issue by ryandevore** [mapbox/DEPRECATED-mapbox-ios-sdk#451]
I'm running into an issue and was hoping to get some assistance from the community.

I'm building an iOS app that uses an online map to style the map view, and the application pulls down places from a server, displays pins, allows searching/etc.  Standard map based app.

The issue I'm running into is that the map can be showing a region, and the user searches for a place and selects that place to view.  When this happens we clear the map of all annotations, add one annotation the user selected, and then center the map on it.

The issue is that if the map has to change zooms levels when selecting the new annotation, the annotation callout does not show after the map zooms and loads.

I've made a barebones sample app to illustrate what is happening:
https://github.com/ryandevore/mapbox_tester

If you run the app and click the 'outside map' button that is going to simulate the situation I'm running into on the real app I'm developing.

One thing that I do notice is that when this occurs,  the selectedAnnotation property is still set, and you cannot tap on the annotation itself, or tapping it does not make the callout appear, unless you tap elsewhere on the map and then back on the annotation.

I've tried a few approaches like delaying the selectAnnotation call until afterMapMove but that does not seem to resolve the issue.

Any assistance or insight would be greatly appreciated!

**Comment by DZamataev** [comment]
Actually delaying the `selectAnnotation` helped me in a similar situation.

**Comment by incanus** [comment]
This sequence here: 

``` objc
[self.mapboxView addAnnotation:annotation];
[self.mapboxView selectAnnotation:annotation animated:YES];
[self.mapboxView setZoom:15 atCoordinate:annotation.coordinate animated:YES];
```

inside your `-replaceAnnotation:` seems suspicious to me. 

First, the annotation will get added. Then, it will be selected with an appearance animation. Last, the map will get moved with an animation. But it's undetermined what will happen between the racing of the annotation selection animation and the movement of the map. 

Since you've got the benefit of open source, you can determine that the movement animation has a certain duration (`0.3s`, though you could also inspect it during debugging): 

https://github.com/mapbox/mapbox-ios-sdk/blob/5b52bb307aca918320bdc7b766fce4d946a95796/MapView/Map/RMMapView.m#L1076

So I would change your code to something like this: 

``` objc
    [self.mapboxView addAnnotation:annotation];
    [self.mapboxView setZoom:15 atCoordinate:annotation.coordinate animated:YES];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.mapboxView selectAnnotation:annotation animated:YES];
    });
```

This works great for me. For completeness, since the `dispatch_after()` can't be updated or cancelled, I'd make sure the user can't interact with the map nor the buttons during the zoom animation.

**Comment by incanus** [comment]
Another approach here uses a little-known property of `UIScrollView`, where you can perform state changes to it with `...animated:NO` but wrap it in a `UIView` animation block to control the duration, timing curve, etc. 

So you could: 

``` objc
[self.mapboxView addAnnotation:annotation];
[UIView animateWithDuration:0.3
                 animations:^{
                     [self.mapView setZoom:15
                              atCoordinate:annotation.coordinate
                                  animated:NO];
                 }
                 completion:^{
                     [self.mapboxView selectAnnotation:annotation 
                                              animated:YES];
                 }];
```

This would implicitly animate the zoom, then upon completion, animate the selection.
