### ISSUE TITLE
Could not load other tile source

### ISSUE THREAD

**Issue by yongpingchen** [mapbox/DEPRECATED-mapbox-ios-sdk#457]
I would like to load tile source from GIS Japan http://portal.cyberjapan.jp/help/development.html#api
Basically, it has almost the same api format as open street map. With an example 
http://cyberjapandata.gsi.go.jp/xyz/std/6/57/23.png, where 6 is zoom level, 57 is x, 23 is y. 
So I create this tile source by
@interace RMGISJapanMapSource : RMAbstractWebMapSource
@end 
@implementation RMGISJapanMapSource
/_some other code_/
-(NSURL *)URLForTile:(RMTile)tile
{
   NSAssert4(((tile.zoom >= self.minZoom) && (tile.zoom <= self.maxZoom)),
              @"%@ tried to retrieve tile with zoomLevel %d, outside source's defined range %f to %f",
              self, tile.zoom, self.minZoom, self.maxZoom);

 return [NSURL URLWithString:[NSString stringWithFormat:@"http://cyberjapandata.gsi.go.jp/xyz/std/%d/%d/%d.png",tile.zoom,tile.x, tile.y]];
}
/_some other code_/
@end
In the view controller where has a RMMapView

-(void)viewDidLoad
 {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    RMGISJapanMapSource *gisJapanSource = [[RMGISJapanMapSource alloc] init];
    [self.mapView addTileSource:gisJapanSource];
    NSArray *tileSources = _mapView.tileSources;
    NSLog(@"tile sources:%d",tileSources.count);
    [self.mapView setContentScaleFactor:1.0f];
    [self.mapView setZoom:7 animated:YES];

 }
But map view still load the Mapbox tile source.

**Comment by mohpor** [comment]
Are your sure you are not seeing Cached version of MapBox tiles?
Plus, how are you initializing your map view? share some code on that too.

**Comment by mohpor** [comment]
You can try using `[self.mapView setTileSource:gisJapanSource];` instead of `addTileSource` counterpart.

**Comment by yongpingchen** [comment]
It doesn't work for me. I check the source code, I found in the layoutsubviews in RMMapview, the block is always call:
  if ( ! _mapScrollView)
    {
        // This will happen after initWithCoder: This needs to happen here because during
        // unarchiving, the view won't have a frame yet and performInitialization...
        // needs a scroll view frame in order to calculate _metersPerPixel.
        // See https://github.com/mapbox/mapbox-ios-sdk/issues/270
        //
        [self performInitializationWithTilesource:[RMMapboxSource new]
                                 centerCoordinate:CLLocationCoordinate2DMake(kDefaultInitialLatitude, kDefaultInitialLongitude)
                                        zoomLevel:kDefaultInitialZoomLevel
                                     maxZoomLevel:kDefaultMaximumZoomLevel
                                     minZoomLevel:kDefaultMinimumZoomLevel
                                  backgroundImage:nil];
    }

**Comment by yongpingchen** [comment]
Hi @mohpor, I saw your issue #433 . Did you load your own tile source successfully?

**Comment by mohpor** [comment]
@yongpingchen , well, it is better now, I'm using the develop branch in my code and it is kindda better, but the problem is still there. The problem arises because of some synchronization problems in tile loading and I'm guessing Justin and his team are working on it to replace the current method to a non-blocking one as probably would be fixed. (lets hope that) But, you and I have different problems here, mine has the blocking problem, yours doesn't load at all (based on my understanding of your problem) I'm sure yours could be fixed easily, I'm willing to help you fix that if you want to. Let me know.

**Comment by yongpingchen** [comment]
@mohpor Thank you.  I did 
[self.mapView setTileSource:gisJapanSource];
But it still didn't work. Is it something wrong I put the setTileSource in the viewDidLoad method?

**Comment by mohpor** [comment]
It is not wrong, but again, you need to review your MapView Initialization I guess.
for example : 

```
self.mapView =[[RMMapView alloc] initWithFrame:self.frame andTilesource:gisJapanSource];
```

**Comment by yongpingchen** [comment]
I think we shouldn't init RMMapView by ourself, should we? I assigned RMMapView by storyboard. 
I think the map view of RMMapView will be init automatically.

**Comment by mohpor** [comment]
Maybe that's the problem here. I am initializing map view in my code and it works good enough. when the default initializer is used (probably `initWithFrame`), the default map box tile source is set as the tile source, you can verify that by checking your debug code, it will log your tile source added to map view. 
What you are saying is not always achievable, for example, my project wraps map box to isolate the client app from future changes and therefore map box sdk has no idea about where it will be used, hence, I need to initialize it myself in code.

**Comment by yongpingchen** [comment]
Thanks @mohpor. I will try with `initWithFrame` in the code firstly. 
I agree with you. In your situation, it needs to create RMMapView by code :)
