### ISSUE TITLE
Coordinates not matching reference zoom level

### ISSUE THREAD

**Issue by ghost** [mapbox/DEPRECATED-mapbox-ios-sdk#469]
Is there a way to match the given pixels (x,y) to pixels of the tile map image tile (e.g. map tile reference zoom level 0) instead of the pixel resolution of the device?
Thank you very much!

**Comment by incanus** [comment]
There isn't a direct way for this, but you can look at code here for a way that this is done for UTFGrid interactivity: 

https://github.com/mapbox/mapbox-ios-sdk/blob/f47ae3d96a27661eb4f888660787bffdf0294492/MapView/Map/RMInteractiveSource.m#L119-L180

There, a `CGPoint()` in screen space (presumably from a tap gesture) is turned into tile-space coordinates in order to determine point of interaction.
