### ISSUE TITLE
Retina support for simplestyle markers

### ISSUE THREAD

**Issue by willwhite** [mapbox/DEPRECATED-mapbox-ios-sdk#47]
@incanus what is necessary to support retina simplestyle markers? Is there a minimum acceptable image size that you'd like to see for big fingers?

**Comment by incanus** [comment]
Technically, touch targets should be 44px, but we're already pushing that and it seems to work fine. Apple's pins aren't anyway. So ideally we need something 2x the size of the medium markers we have now. Additionally, maps aren't automatically retina, so even with retina markers, the map tiles are fuzzy.

**Comment by incanus** [comment]
As far as what happens here after they 2x versions are available on the API, we'd manually need to determine when on retina and request the 2x versions, unlike local assets where a request for `blah.png` will auto-grab `blah@2x.png` if necessary (and available). Determining if on retina is easy (`[[UIScreen mainScreen] scale] > 1.0`) But otherwise this is easy.

**Comment by incanus** [comment]
Copying @samanpwbb here. Where is the best place to file this, ideally to get an XL size variant?

**Comment by incanus** [comment]
Seeing this on the server side now, so will add support to SDK.
