### ISSUE TITLE
enhancements for multi-touch and multi-tap

### ISSUE THREAD

**Issue by whiteboxcode** [mapbox/DEPRECATED-mapbox-ios-sdk#52]
Any way we could get these added in?
https://github.com/route-me/route-me/pull/128

I am currently trying to get some markers from a server AFTER a user zooms in using a pinch gesture, the afterMapZoom which currently exists is called several times instead of once.  Causes us a real issue as it hammers the server.

Please let me know if I can help in any way.

**Comment by incanus** [comment]
Interesting. Hadn't seen these. It likely won't merge cleanly, due to us & upstream (Alpstein) being pretty divergent forks from route-me core right now. Another thing that jumps out is the before/after rotate callbacks, and we don't yet support rotation (see #19). 

Best way to contribute would be an adapted pull request of your own. You could submit to us, or ideally, to [Alpstein](https://github.com/Alpstein/route-me) directly. 

It's pretty low priority for us since no one else is asking for it, but I'll keep it open here in the event some time frees up.

**Comment by incanus** [comment]
We are more or less doing this now with the current `RMMapViewDelegate` methods like `beforeMapMove:byUser:` etc.
