### ISSUE TITLE
Support for conditional GETs

### ISSUE THREAD

**Issue by willwhite** [mapbox/DEPRECATED-mapbox-ios-sdk#66]
Eventually, it might make sense to have the SDK refresh tiles based on a conditional GETs where tile data is only transfered from the server if the tile has changed.

This would only make sense for a time based cache expiration policy. Like tiles expire after two weeks and then the SDK checks the server to see if they've changed. If they haven't we just use the same tiles for another two weeks.

Seems like pretty low priority for now.

**Comment by incanus** [comment]
In my mind there are two approaches that could be taken here: 
- Reactively as part of the cache touch pipeline. 
  
  Currently when tiles are needed for screen: 
  - Cache is checked for tile
  - Network is hit if tile doesn't exist in cache
  - Tile is cached for future use
  - All tiles are subject to garbage collection (probability-based) purge during this process _(does not involve network activity)_
  
  Possibly firing off `GET` requests for tiles other than the one in question seems dicey here unless some sort of background queue were setup in which to place them. But that essentially means any map loads could possibly trigger GC, which could possibly trigger a bunch of background `GET` activity for tiles. 
  
  Firing off a `GET` request for _only_ the tile in question is also not great because it puts us in the situation of relatively frequently firing off network requests for tiles that we already have locally, e.g.: 
  - When we cached the tile, headers said check back in two weeks
  - Post-two weeks when tile is requested & found in cache, we fire off a `GET` first
  - When the conditional `GET` comes back negative (nothing new), we update cached header time for tile & serve existing cache
  - Two weeks later, we repeat
  - We have now introduced relatively unnecessary `GET` requests into a local cache pipeline, which holds up rendering
  
  Weak point to argument: I could use better numbers about average lifetimes of network tiles. 
- Proactively in the background based on cache age. This also seems like bad territory to venture into as no mobile developer wants random stuff running in the background relatively unpredictably. Combine this with the need for background API use since odds are the app is not the one running most of the time and it's a tough sell. 

For the first point, I think the frequency of occurrence of the extra `GET` requests is not worth the tradeoff given that we're not hearing about people not having fresh enough maps (though: maybe they don't know?)

The existing API of blowing away the whole cache or cache for a particular map layer is probably sufficient. App devs can set a defaults key e.g. `clearedCache1.3` in order to synchronize global cache clears with app releases in order to freshen things up if they so desire. 

/cc @miccolis since we were talking about this recently.

**Comment by incanus** [comment]
Related: https://github.com/mapbox/mapbox-ios-sdk/pull/274

**Comment by incanus** [comment]
We are ok here as tiles aren't downloaded unless they are missing from local cache anyway.
