### ISSUE TITLE
No data connection can hang main thread

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#91]
If the app has a valid Wi-Fi connection, but ultimately no data connection (e.g. the router is no data, but the iPad is connected to the router) then MapBox blocks indefinitely in initWithReferenceURL:

[NSString stringWithContentsOfURL:referenceURL encoding:NSUTF8StringEncoding error:nil])

Because this runs in the main thread, it just blocks the whole app "forever" :-/

**Comment by incanus** [comment]
I think for this one, the eventual solution will be integration with [Reachability](http://developer.apple.com/library/ios/#samplecode/Reachability/Introduction/Intro.html) (or perhaps an alternative like [this one](https://github.com/tonymillion/Reachability)) to detect true current connection status. However, I'm not sure about putting that in at this point in the [0.4.0](https://github.com/mapbox/mapbox-ios-sdk/issues?labels=&milestone=2&page=1&sort=updated&state=open) cycle, plus needing to link in `SystemConfiguration.framework` in order to use the SDK. However, I would like to eventually. 

I think for now, it's probably better if you use Reachability and do an online/offline test yourself before trying the initialization. Unless you can think of a better alternative that doesn't hang.

**Comment by russellquinn** [comment]
I agree with the above, although shouldn't stringWithContentsOfURL be called in a separate thread, so that it doesn't block?

**Comment by incanus** [comment]
Hmm, I'm not sure of a way to do that in an `init` context, which needs to return synchronously. The dev could do the `init` of the tile source async and then update the map view with it in the main thread. 

This does need some thought, though. I added the `init` as a convenience to avoid needing to fetch JSON and do stuff with it, for easier integration with our hosting. Maybe a GCD approach with a `successBlock` that actually changes the tile source on success, with some fallback plan like OSM or a local, offline source.

**Comment by futureshape** [comment]
This is also related to #83 - if we allow people to bulk-download tiles for offline use, it must be possible to launch the app without an internet connection.

One solution might be to allow developers to include a fallback JSON configuration file in their app in case the library can't fetch the one from the network?

**Comment by incanus** [comment]
Yeah, good point. Right now, probably the best approach is to grab the TileJSON for the source when available, cache it, and in the future, do your own reachability tests before either trying to refetch or just pointing to the cached one in a `NSURL`.

**Comment by incanus** [comment]
I've been doing some thinking on this, and I still think it's best handled in the client code, just like #82. There are too  many bits in the SDK to cover in case of being or going offline. It'd be better for one of two situations to be handled by client apps, depending upon need: 
1. No offline mode needed or supported. Detect net change and replace map view with alternative view, be it warning/error, static map image, or what have you. 
2. Offline mode needed and supported. Check for net before attempting to get TileJSON and/or cache it locally for instantiation. Use #83 bulk downloader to best prepare for it and/or utilize a long-running tile cache to have tiles ready. Use things like `-[RMMapView reloadTilesource:]` and friends when net is back, if desired. 

Also, worth mentioning a good alternative to Apple's Reachability class: 

https://github.com/tonymillion/Reachability
