### ISSUE TITLE
Draw a RMShape onto the map

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#97]
It should be simple I guess, but I can't see how to get the RMShape to display on the map. 

Can someone please point me to some documentation or give me a simple example of how to do it?

So far I am doing...

``` objective-c
RMShape *route = [[RMShape alloc] initWithView:self.mapView];
[route setLineWidth:3.0];
[route setLineColor:[UIColor colorWithRed:1.f green:0.f blue:0.f alpha:1.f]];
[route moveToCoordinate:CLLocationCoordinate2DMake(47.089634, 15.429118)];
[route addLineToCoordinate:CLLocationCoordinate2DMake(47.089784, 15.429182)];
[route addLineToCoordinate:CLLocationCoordinate2DMake(47.089849, 15.429182)];
```

**Comment by incanus** [comment]
Have a look at `RMAnnotation`. Much like Apple's MapKit, you need to add an annotation to the map first, then either provide the `RMShape` directly as `annotation.layer` or via the `RMMapViewDelegate` callback `mapView:layerForAnnotation:` in order to make it visible.

**Comment by asutula** [comment]
So, if you're adding a polyline shape to the map via a RMAnnotation, what do you use for the annotation coordinate? Or do you not provide a coordinate and provide a RMProjectedBoundingBox? I'm assuming something like this is necessary so that the map knows when it needs to display the annotation based on the viewable area of the map. Thanks.

**Comment by incanus** [comment]
I don't recall offhand how the `coordinate` works -- it came from the upstream project. However I do know that it's good to set the `boundingBox`, ideally via either specifying corners with `setBoundingBoxCoordinatesSouthWest:northEast:` or by passing the array of locations you used to generate the shape to `setBoundingBoxFromLocations:`. 

I will flag an issue to look into this deeper and possibly auto-set the bounding box internally, since that sounds like it makes the most sense to me. If your shape doesn't change, why should you have to mess around with a bounding box?

**Comment by asutula** [comment]
Thanks for the reply. I'll give that a try. Your suggested enhancement make sense to me.
